name: Commitpipeline
run-name: ${{ github.actor }} made a commit

on:
  push:
    branches: 
      - ftr/*


jobs:
  
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Test with Checkov
