name: Terraform commit pipeline
run-name: ${{ github.actor }} made a commit to infrastructure

on:
  push:
    branches: [ main ]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        id: start
        with:
          task: start-measurement
          
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Check Terraform formatting
        uses: dflook/terraform-fmt-check@v1
        with:
          path: "./infrastructure/"
          
      - name: Get Measurement
        id: get
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          
      - name: Display Results
        if: always()
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results
  
  lint-code:
    runs-on: ubuntu-latest
    needs: format-code
    steps:
      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        id: start
        with:
          task: start-measurement
          
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Check linting of Terraform code
        uses: devops-infra/action-tflint@v0.3
        with:
          dir_filter: infrastructure/
          
      - name: Get Measurement
        id: get
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          
      - name: Display Results
        if: always()
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results

  validate:
    runs-on: ubuntu-latest
    needs: lint-code
    steps:
      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        id: start
        with:
          task: start-measurement
          
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Validate Terraform
        uses: dflook/terraform-validate@v1
        with:
          path: "./infrastructure/"
          
      - name: Get Measurement
        id: get
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          
      - name: Display Results
        if: always()
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results

  checkov-scan:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        id: start
        with:
          task: start-measurement
          
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Check infrastructure code with Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          check: 'HIGH, CRITICAL'
          directory: infrastructure/
          output_format: cli
          output_file_path: console
          
      - name: Get Measurement
        id: get
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          
      - name: Display Results
        if: always()
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results