name: mlflow-commit.yml
on:
  push:
    branches:
      - main

jobs:
  mlflow-build-push:
    name: Build MLflow Docker image, check for vulneratibilities and push
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up BuildX
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN}}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Build Docker image
        run: docker build -f mlflow.Dockerfile -t mlflow:${{ github.sha }} .
      - id: measurement-6
        name: Record Measurement After Build Docker image
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Build Docker image
          task: get-measurement
      - name: Push to Docker Hub
        run: 'docker tag mlflow:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/mlflow:${{
          github.sha }}

          docker tag mlflow:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/mlflow:latest

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow:${{ github.sha }}

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow:latest

          '
      - id: measurement-8
        name: Record Measurement After Push to Docker Hub
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Push to Docker Hub
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption1
          path: total_energy_consumption1.json
run-name: ${{ github.actor }} made a commit to MLflow files
